artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://raw.githubusercontent.com/jaydeepIneuron007/Dataset/main/chest_xray.zip
  local_data_file: artifacts/data_ingestion/chest_xray.zip
  unzip_dir: artifacts/data_ingestion
